language: csharp
sudo: required
solution: ./src/DataGround.sln
dotnet: 1.1.0
matrix:
  include:
    - dotnet: 1.1.0
      mono: none
      dist: trusty
before_install:
  - chmod +x ./ci.sh
script:
  - ./ci.sh